### ISSUE TITLE
Bot thinks URL is a username

### ISSUE THREAD

**Issue by heraldofsolace** [Boidushya/imposterBot#1]
Due to the way the regex is set any path of a URL that ends in 'u' is considered a username.

Check this [comment](https://www.reddit.com/r/modelmakers/comments/j4rgyv/-/g7mne1y)

**Comment by boidushya** [comment]
I am aware of this issue (actually i kinda knew this would happen before i made the regex and even added that to [dev log 1](https://www.reddit.com/user/botwasnotanimposter/comments/iwauje/what_i_do/) very [seriously](https://i.paste.pics/a47571b570ba60bfac1d5f721fd61b96.png). I am, however, open to suggestions or pull requests for a different regex that handles usernames better!
Meanwhile i will try to come up with a more stable regex but no promises...
Thanks for raising the issue nevertheless!

**Comment by heraldofsolace** [comment]
Probably the `.*` in front of the regex is the culprit here. I wonder how Reddit detects usernames
